- hosts: managers
  become: yes
  gather_facts: false
  tasks:
    - name: initialize the cluster with config file
      shell: docker swarm init --advertise-addr {{ manager_public_ip }} >> swarm-init.log
      register: swarm_init
      args:
        chdir: $HOME
        creates: swarm-init.log

    - name: get join token
      when: swarm_init is succeeded
      shell: docker swarm join-token -q manager
      register: join_token

- hosts: workers
  become: yes
  tasks:
    - set_fact: join_token={{ hostvars['manager'].join_token }}

    - name: join cluster
      shell: docker swarm join --token {{ join_token.stdout}} {{ manager_public_ip }}:2377 >> swarm-join.log
      args:
        chdir: $HOME
        creates: swarm-join.log
